// Hand-authored OpeningSpecs (the core openings). Generated by scripts/register-specs.ts —
// add a spec file and re-run it rather than editing this by hand.
import type { OpeningSpec } from "../spec";
import { alapinSicilian } from "./alapin-sicilian";
import { alekhine } from "./alekhine";
import { benkoGambit } from "./benko-gambit";
import { benoni } from "./benoni";
import { bogoIndian } from "./bogo-indian";
import { caroKann } from "./caro-kann";
import { dutchDefence } from "./dutch-defence";
import { englishOpening } from "./english-opening";
import { fourKnights } from "./four-knights";
import { frenchDefence } from "./french-defence";
import { grunfeld } from "./grunfeld";
import { italianGame } from "./italian-game";
import { kingsIndian } from "./kings-indian";
import { larsenOpening } from "./larsen";
import { londonSystem } from "./london-system";
import { nimzoIndian } from "./nimzo-indian";
import { openGamesBlack } from "./open-games-black";
import { pirc } from "./pirc";
import { queensGambit } from "./queens-gambit";
import { reti } from "./reti";
import { ruyLopez } from "./ruy-lopez";
import { scandinavian } from "./scandinavian";
import { scotchGame } from "./scotch-game";
import { semiSlav } from "./semi-slav";
import { sicilianDefence } from "./sicilian-defence";
import { slavDefence } from "./slav-defence";
import { viennaGame } from "./vienna-game";

export const SPECS: OpeningSpec[] = [alapinSicilian, alekhine, benkoGambit, benoni, bogoIndian, caroKann, dutchDefence, englishOpening, fourKnights, frenchDefence, grunfeld, italianGame, kingsIndian, larsenOpening, londonSystem, nimzoIndian, openGamesBlack, pirc, queensGambit, reti, ruyLopez, scandinavian, scotchGame, semiSlav, sicilianDefence, slavDefence, viennaGame];
