// Coached openings: every hand-authored spec. Regenerated by scripts/register-specs.ts.
export const CORE_OPENING_IDS = [
  "italian-game",
  "london-system",
  "queens-gambit",
  "vienna-game",
  "caro-kann",
  "scandinavian",
  "french-defence",
  "open-games-black",
  "slav-defence",
  "kings-indian",
  "larsen",
  "alapin-sicilian",
  "alekhine",
  "benko-gambit",
  "benoni",
  "bogo-indian",
  "dutch-defence",
  "english-opening",
  "four-knights",
  "grunfeld",
  "nimzo-indian",
  "pirc",
  "reti",
  "ruy-lopez",
  "scotch-game",
  "semi-slav",
  "sicilian-defence",
] as const;

export type CoreOpeningId = (typeof CORE_OPENING_IDS)[number];

export function isCore(id: string): boolean {
  return (CORE_OPENING_IDS as readonly string[]).includes(id);
}

/** What the home screen shows. Home answers "what should I play?", so it stays
 *  a short recommendation even now that every opening is coached in depth. The
 *  catalogue on the Openings tab lists all of them. Order = display order. */
export const FEATURED_OPENING_IDS = [
  "italian-game",
  "london-system",
  "larsen",
  "queens-gambit",
  "vienna-game",
  "caro-kann",
  "scandinavian",
  "french-defence",
  "open-games-black",
  "slav-defence",
  "kings-indian",
] as const;

export function isFeatured(id: string): boolean {
  return (FEATURED_OPENING_IDS as readonly string[]).includes(id);
}
