// Regenerates src/content/specs/index.ts from whatever spec files exist, and
// makes every hand-authored spec a core opening. Run after adding spec files.
//
// Run: npx tsx scripts/register-specs.ts

import fs from "node:fs";
import path from "node:path";

const dir = path.resolve("src/content/specs");
const files = fs.readdirSync(dir).filter((f) => f.endsWith(".ts") && f !== "index.ts").sort();

const entries = files.map((f) => {
  const src = fs.readFileSync(path.join(dir, f), "utf8");
  const m = src.match(/export const (\w+)\s*:\s*OpeningSpec/);
  const id = src.match(/^\s*id:\s*"([^"]+)"/m)?.[1];
  if (!m || !id) throw new Error(`${f}: could not find "export const <name>: OpeningSpec" and an id`);
  return { file: f.replace(/\.ts$/, ""), name: m[1], id };
});

const index = [
  "// Hand-authored OpeningSpecs (the core openings). Generated by scripts/register-specs.ts —",
  "// add a spec file and re-run it rather than editing this by hand.",
  'import type { OpeningSpec } from "../spec";',
  ...entries.map((e) => `import { ${e.name} } from "./${e.file}";`),
  "",
  `export const SPECS: OpeningSpec[] = [${entries.map((e) => e.name).join(", ")}];`,
  "",
].join("\n");
fs.writeFileSync(path.join(dir, "index.ts"), index);

// core.ts keeps the original ten first (their display order is deliberate),
// then everything else alphabetically.
const corePath = path.resolve("src/content/core.ts");
const core = fs.readFileSync(corePath, "utf8");
const coreBlock = core.match(/export const CORE_OPENING_IDS = \[([\s\S]*?)\] as const;/)?.[1] ?? "";
const existing = [...new Set([...coreBlock.matchAll(/"([a-z0-9-]+)"/g)].map((m) => m[1]))];
const ordered = [...existing, ...entries.map((e) => e.id).filter((id) => !existing.includes(id)).sort()];
const body = ordered.map((id) => `  "${id}",`).join("\n");
const next = core.replace(/export const CORE_OPENING_IDS = \[[\s\S]*?\] as const;/, `export const CORE_OPENING_IDS = [\n${body}\n] as const;`);
fs.writeFileSync(corePath, next);

console.log(`registered ${entries.length} specs; ${ordered.length} core openings`);
for (const e of entries) console.log(`  ${e.id.padEnd(26)} ${e.name}`);
